### ISSUE TITLE
huge memory consumption

### ISSUE THREAD

**Issue by nsurgeon** [RTshok/aes-enc-dec-tool#2]
in order to encrypt/decrypt data function allocates 2 memory block which are the same size as input file 
AES is a block cypher - could you consider to reduce memory consumption to 2 memory block which are in size as a single AES frame
CRC also can be calculated during encryption

**Comment by SerhiienkoRT** [comment]
fixed!

**Comment by SerhiienkoRT** [comment]
Added an ability to run the program with different block size (up to 8192). This lead to enormous improvement in performance ! Also added some simple test script(written in bash), which could be run to ensure in workability of a program
